general:
    count: 100
    log_path: "C:/Users/anush/Documents/Courses/ERMD/data_sets/malware-logs-for-semester-project"
    output_dir: "C:/Users/anush/Documents/Courses/ERMD/data_sets/results/"
    log_pattern: "*.log"

analysis:
    self_rep: 100
    persistence: 100
    injection: 100
    temp_exe: 100

