general:
    count: 100
    log_path: "/mnt/g/Files/School Files/2020 WI/17632 Runtime Malware Detection/logs"
    output_dir: "/home/magicannon/proj_malware/output"
    log_pattern: "*.log"

analysis:
    self_rep: 100
    persistence: 100
    injection: 100
    temp_exe: 100

